import type { Fanfic } from '@/types'

export const MOCK_FANFICS: Fanfic[] = [
  {
    id: '1',
    title: 'Между строк',
    description: 'Гарри Поттер никогда не думал, что случайная записка, найденная в библиотеке, изменит его жизнь. Драко Малфой — последний, кого он ожидал увидеть по другую сторону переписки.',
    author_name: 'Лунная_Соната',
    author_id: 'a1',
    fandoms: ['Гарри Поттер'],
    pairings: [{ characters: ['Гарри Поттер', 'Драко Малфой'], is_highlight: true }],
    tags: [{ name: 'AU', is_adult: false }, { name: 'Флафф', is_adult: false }, { name: 'Эпистолярный жанр', is_adult: false }],
    direction: 'Слэш',
    rating: 'PG-13',
    completion_status: 'Завершён',
    likes: 4821,
    trophies: 312,
    words_count: 187000,
    chapters_count: 34,
    comments_count: 1203,
    cover_url: undefined,
    ficbook_url: 'https://ficbook.net/readfic/1',
    is_hot: true,
    ai_scores: { romance_score: 0.85, fluff_score: 0.72, angst_score: 0.31, drama_score: 0.44, narrative_depth: 0.78, writing_quality: 0.81 },
  },
  {
    id: '2',
    title: 'Осколки льда',
    description: 'После войны Лoki пытается найти своё место в мире. Тор не оставляет его в покое. Медленное восстановление, попытки понять что такое семья, и неожиданная нежность там, где её совсем не ждёшь.',
    author_name: 'Звёздный_Ветер',
    author_id: 'a2',
    fandoms: ['Мстители', 'Тор'],
    pairings: [{ characters: ['Локи', 'Тор'], is_highlight: false }],
    tags: [{ name: 'Ангст', is_adult: false }, { name: 'Hurt/Comfort', is_adult: false }, { name: 'Восстановление', is_adult: false }, { name: 'Медленное развитие', is_adult: false }],
    direction: 'Слэш',
    rating: 'R',
    completion_status: 'Завершён',
    likes: 7203,
    trophies: 891,
    words_count: 342000,
    chapters_count: 67,
    comments_count: 3412,
    cover_url: undefined,
    ficbook_url: 'https://ficbook.net/readfic/2',
    is_hot: false,
    ai_scores: { angst_score: 0.91, romance_score: 0.62, drama_score: 0.88, narrative_depth: 0.85, writing_quality: 0.88 },
  },
  {
    id: '3',
    title: 'Кофе и катастрофы',
    description: 'Гермиона открыла небольшую кофейню. Драко случайно стал её постоянным клиентом. Никто из них не планировал влюбляться — но кофе имеет странное свойство сближать людей.',
    author_name: 'Чернильная_Роза',
    author_id: 'a3',
    fandoms: ['Гарри Поттер'],
    pairings: [{ characters: ['Гермиона Грейнджер', 'Драко Малфой'], is_highlight: true }],
    tags: [{ name: 'AU — Немагический', is_adult: false }, { name: 'Романтика', is_adult: false }, { name: 'Комедия', is_adult: false }, { name: 'Флафф', is_adult: false }],
    direction: 'Гет',
    rating: 'PG-13',
    completion_status: 'Завершён',
    likes: 3109,
    trophies: 204,
    words_count: 95000,
    chapters_count: 18,
    comments_count: 876,
    cover_url: undefined,
    ficbook_url: 'https://ficbook.net/readfic/3',
    is_hot: false,
    ai_scores: { romance_score: 0.93, fluff_score: 0.88, humor_score: 0.71, angst_score: 0.08, writing_quality: 0.76 },
  },
  {
    id: '4',
    title: 'Последний свет Арды',
    description: 'Что если бы Феанор не погиб в Дагор-нуин-Гилиат? Альтернативная история Первой эпохи, где один выживший меняет всё. Масштабная эпопея о гордости, искуплении и цене выбора.',
    author_name: 'Серебряный_Клинок',
    author_id: 'a4',
    fandoms: ['Сильмариллион', 'Властелин колец'],
    pairings: [],
    tags: [{ name: 'AU', is_adult: false }, { name: 'Эпик', is_adult: false }, { name: 'Политика', is_adult: false }, { name: 'Война', is_adult: false }],
    direction: 'Джен',
    rating: 'R',
    completion_status: 'В процессе',
    likes: 2847,
    trophies: 445,
    words_count: 521000,
    chapters_count: 89,
    comments_count: 2103,
    cover_url: undefined,
    ficbook_url: 'https://ficbook.net/readfic/4',
    is_hot: true,
    ai_scores: { adventure_score: 0.94, drama_score: 0.89, mystery_score: 0.61, narrative_depth: 0.95, writing_quality: 0.92 },
  },
  {
    id: '5',
    title: 'Пять причин ненавидеть соседа',
    description: 'Сакура переехала в новую квартиру и сразу поняла: её сосед — невыносим. Громкая музыка в 2 ночи, постоянные гости и самодовольная ухмылка — это Саске Учиха во всей красе.',
    author_name: 'Сакурацвет',
    author_id: 'a5',
    fandoms: ['Наруто'],
    pairings: [{ characters: ['Сакура Харуно', 'Саске Учиха'], is_highlight: true }],
    tags: [{ name: 'AU — Современность', is_adult: false }, { name: 'Романтика', is_adult: false }, { name: 'Комедия положений', is_adult: false }, { name: 'Враги-в-любовники', is_adult: false }],
    direction: 'Гет',
    rating: 'PG-13',
    completion_status: 'Завершён',
    likes: 5621,
    trophies: 378,
    words_count: 134000,
    chapters_count: 24,
    comments_count: 1897,
    cover_url: undefined,
    ficbook_url: 'https://ficbook.net/readfic/5',
    is_hot: false,
    ai_scores: { romance_score: 0.87, humor_score: 0.82, fluff_score: 0.65, angst_score: 0.21, writing_quality: 0.74 },
  },
  {
    id: '6',
    title: 'Тёмные воды',
    description: 'Детектив Эрвин Смит расследует серию убийств в портовом городе. Единственный свидетель — странный молодой человек по имени Леви, который знает больше, чем говорит.',
    author_name: 'Штормовой_Берег',
    author_id: 'a6',
    fandoms: ['Атака титанов'],
    pairings: [{ characters: ['Эрвин Смит', 'Леви Акерман'], is_highlight: true }],
    tags: [{ name: 'AU — Детектив', is_adult: false }, { name: 'Нуар', is_adult: false }, { name: 'Тайна', is_adult: false }, { name: 'Медленное развитие', is_adult: false }],
    direction: 'Слэш',
    rating: 'R',
    completion_status: 'Завершён',
    likes: 3988,
    trophies: 267,
    words_count: 278000,
    chapters_count: 51,
    comments_count: 1544,
    cover_url: undefined,
    ficbook_url: 'https://ficbook.net/readfic/6',
    is_hot: false,
    ai_scores: { mystery_score: 0.92, drama_score: 0.85, angst_score: 0.67, romance_score: 0.54, narrative_depth: 0.88, writing_quality: 0.86 },
  },
]

export function searchMockFanfics(query: string): Fanfic[] {
  if (!query.trim()) return MOCK_FANFICS
  const q = query.toLowerCase()
  return MOCK_FANFICS.filter(f =>
    f.title.toLowerCase().includes(q) ||
    f.description?.toLowerCase().includes(q) ||
    f.fandoms.some(fandom => fandom.toLowerCase().includes(q)) ||
    f.author_name.toLowerCase().includes(q) ||
    f.tags.some(t => t.name.toLowerCase().includes(q)) ||
    f.pairings.some(p => p.characters.some(c => c.toLowerCase().includes(q)))
  )
}
